DROP DATABASE IF EXISTS craigslist;

CREATE DATABASE craigslist;

\c craigslist

CREATE TABLE "regions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "region" varchar,
  "createdon" timestamp
);

CREATE TABLE "locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location" varchar,
  "region_id" integer,
  "createdon" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) NOT NULL,
  "preferred_region_id" integer,
  "createdon" timestamp
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(255)
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "text" text,
  "user_id" integer,
  "location_id" integer,
  "region_id" integer,
  "status" varchar,
  "createdon" timestamp
);

CREATE TABLE "post_category" (
  "post_id" integer,
  "category_id" integer
);

COMMENT ON COLUMN "posts"."text" IS 'Content of the post';

ALTER TABLE "locations" ADD FOREIGN KEY ("region_id") REFERENCES "regions" ("id");
ALTER TABLE "users" ADD FOREIGN KEY ("preferred_region_id") REFERENCES "regions" ("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("region_id") REFERENCES "regions" ("id");
ALTER TABLE "post_category" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
ALTER TABLE "post_category" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");


INSERT INTO regions (region, createdon)
VALUES ('North America', '2023-05-26'),
       ('Europe', '2023-05-26'),
       ('Asia', '2023-05-26');

INSERT INTO locations (location, region_id, createdon)
VALUES ('New York', 1, '2023-05-26'),
       ('London', 2, '2023-05-26'),
       ('Tokyo', 3, '2023-05-26');

INSERT INTO users (username, preferred_region_id, createdon)
VALUES ('Tom', 1, '2023-05-26'),
       ('Dick', 2, '2023-05-26'),
       ('Harry', 3, '2023-05-26');

INSERT INTO categories (category)
VALUES ('Technology'),
       ('Sports'),
       ('Entertainment');

INSERT INTO posts (title, text, user_id, location_id, region_id, status, createdon)
VALUES ('Tech Post', 'This is a tech post', 1, 1, 1, 'Published', '2023-05-26'),
       ('Sports Post', 'This is a sports post', 2, 2, 2, 'Published', '2023-05-26'),
       ('Entertainment Post', 'This is an entertainment post', 3, 3, 3, 'Published', '2023-05-26');

INSERT INTO post_category (post_id, category_id)
VALUES (1, 1),
       (2, 2),
       (3, 3);

