DROP DATABASE IF EXISTS medical;

CREATE DATABASE medical;

\c medical

CREATE TABLE "medical_centers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "location" varchar
);

CREATE TABLE "doctors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "speciality" varchar(255) NOT NULL,
  "medical_center_id" int
);

CREATE TABLE "patients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "age" integer,
  "birth_date" timestamp
);

CREATE TABLE "diseases" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "disease" varchar(255) NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE "diagnosis" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "visit_id" int NOT NULL,
  "diagnosis_name" varchar(255) NOT NULL,
  "comments" text,
  "createdon" timestamp
);

CREATE TABLE "visits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int,
  "patient_id" int,
  "medical_center_id" int,
  "diagnosis_id" int,
  "visit_date" timestamp
);

CREATE TABLE "doctor_patient" (
  "doctor_id" int,
  "patient_id" int
);

CREATE TABLE "diagnosis_disease" (
  "diagnosis_id" int,
  "disease_id" int
);

ALTER TABLE "doctors" ADD FOREIGN KEY ("medical_center_id") REFERENCES "medical_centers" ("id");

ALTER TABLE "visits" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id"),
ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id"),
ADD FOREIGN KEY ("medical_center_id") REFERENCES "medical_centers" ("id"),
ADD FOREIGN KEY ("diagnosis_id") REFERENCES "diagnosis" ("id");

ALTER TABLE "doctor_patient" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id"),
ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "diagnosis" ADD FOREIGN KEY ("visit_id") REFERENCES "visits" ("id");

ALTER TABLE "diagnosis_disease" ADD FOREIGN KEY ("diagnosis_id") REFERENCES "diagnosis" ("id"),
ADD FOREIGN KEY ("disease_id") REFERENCES "diseases" ("id");


INSERT INTO medical_centers (name, location)
VALUES ('Central Hospital', 'Central City'),
       ('West Clinic', 'West City'),
       ('North Health Center', 'North City');

INSERT INTO doctors (name, speciality, medical_center_id)
VALUES ('Dr. Adams', 'Cardiology', 1),
       ('Dr. Baker', 'Neurology', 2),
       ('Dr. Clark', 'Dermatology', 3);

INSERT INTO patients (name, age, birth_date)
VALUES ('John Doe', 50, '1973-05-26'),
       ('Jane Smith', 35, '1988-06-15'),
       ('Robert Johnson', 45, '1978-07-20');

INSERT INTO diseases (disease, description)
VALUES ('Hypertension', 'A condition where the force of the blood against the artery walls is too high.'),
       ('Alzheimer''s Disease', 'A progressive disorder that causes brain cells to waste away (degenerate) and die.'),
       ('Eczema', 'A condition that makes your skin red and itchy.');

INSERT INTO visits (doctor_id, patient_id, medical_center_id, visit_date)
VALUES (1, 1, 1, '2023-05-26 00:00:00'),
       (2, 2, 2, '2023-06-01 00:00:00'),
       (3, 3, 3, '2023-06-15 00:00:00');

INSERT INTO diagnosis (visit_id, diagnosis_name, comments, createdon)
VALUES (1, 'Diagnosis 1', 'Initial Diagnosis', '2023-05-26 00:00:00'),
       (2, 'Diagnosis 2', 'Follow-up Diagnosis', '2023-06-01 00:00:00'),
       (3, 'Diagnosis 3', 'Final Diagnosis', '2023-06-15 00:00:00');

UPDATE visits SET diagnosis_id = 1 WHERE id = 1;
UPDATE visits SET diagnosis_id = 2 WHERE id = 2;
UPDATE visits SET diagnosis_id = 3 WHERE id = 3;

INSERT INTO doctor_patient (doctor_id, patient_id)
VALUES (1, 1),
       (2, 2),
       (3, 3);

INSERT INTO diagnosis_disease (diagnosis_id, disease_id)
VALUES (1, 1),
       (2, 2),
       (3, 3);
